#!/bin/bash

serverbackup(){
	echo -e -n "\nEnter remote SSH username or press 'd' for default (root): "
	read remote_user
	if [ "$remote_user" = "d" ] || [ -z "$remote_user" ]; then
		remote_user="root"
	fi
	remote="${remote_user}@${server}"

	echo -e -n "\nIs the remote server Linux or Windows? Enter 'l' or 'w' (default: l): "
	read remote_os_input
	if [ "$remote_os_input" = "w" ] || [ "$remote_os_input" = "W" ]; then
		remote_os="windows"
	else
		remote_os="linux"
	fi
	CURRENT_REMOTE_OS="$remote_os"

	if [ "$remote_os" = "windows" ]; then
		default_remote_dir="C:/clone/"

		if scp -O 2>&1 | grep -qi "unknown option"; then
			scp_opts=""
		else
			scp_opts="-O"
		fi
	else
		default_remote_dir="$DEFAULT_DIR"
		scp_opts=""
	fi

	echo -e -n "\nBack up a file (f) or a folder (d)? "
	read type

	echo -e -n "\nEnter remote destination folder or press 'd' for default ($default_remote_dir): "
	read dest
	if [ "$dest" = "d" ] || [ -z "$dest" ]; then
		dest="$default_remote_dir"
	fi
	dest="${dest%/}/"

	remote_dir_exists "$remote" "$dest" "$remote_os"
	if [ $? -ne 0 ]; then
		echo -e "\nFolder '$dest' does not exist on $server. Creating it..."
		remote_mkdir "$remote" "$dest" "$remote_os"
		remote_dir_exists "$remote" "$dest" "$remote_os"
		if [ $? -ne 0 ]; then
			echo -e  "\nError: could not connect to server or create remote folder '$dest'."
			return 1
		fi
		echo -e "\nRemote folder created."
	fi

	if [ "$type" = "f" ]; then
		echo -e -n "\nEnter file name to back up: "
		read filename
		if [ ! -f "$filename" ]; then
			echo -e "\nError: file '$filename' does not exist."
			return 1
		fi
		base=$(basename "$filename")
		check_existing_remote "$remote" "$dest" "$base" "$remote_os" || return 1

		remote_target="${dest}${base}_backup${TIMESTAMP}"
		remote_temp="${remote_target}.partial"

		CURRENT_REMOTE_USER="$remote_user"
		CURRENT_REMOTE_HOST="$server"
		CURRENT_REMOTE_PATH="$remote_temp"

		scp $scp_opts "$filename" "$remote:$remote_temp"
		scp_status=$?

		if [ $scp_status -eq 0 ]; then
			remote_rename "$remote" "$remote_temp" "$remote_target" "$remote_os"
			if [ $? -eq 0 ]; then
				echo -e "\nFile backed up successfully to $server:$remote_target"
			else
				echo -e "\nError: transfer succeeded but could not finalize the remote file."
				remote_remove "$remote" "$remote_temp" "$remote_os"
			fi
		else
			echo -e "\nError: server file backup failed."
			remote_remove "$remote" "$remote_temp" "$remote_os"
		fi

		CURRENT_REMOTE_USER=""
		CURRENT_REMOTE_HOST=""
		CURRENT_REMOTE_PATH=""
		CURRENT_REMOTE_OS=""

	elif [ "$type" = "d" ]; then
		echo -e -n "\nEnter folder name to back up: "
		read foldername
		if [ ! -d "$foldername" ]; then
			echo -e "\nError: folder '$foldername' does not exist."
			return 1
		fi
		base=$(basename "$foldername")
		check_existing_remote "$remote" "$dest" "$base" "$remote_os" || return 1

		archive="/tmp/${base}_backup${TIMESTAMP}.tar.gz"
		remote_target="${dest}${base}_backup${TIMESTAMP}.tar.gz"
		remote_temp="${remote_target}.partial"
		CURRENT_TARGET="$archive"

		run_with_progress "Compressing folder" "$archive" \
			tar -czf "$archive" -C "$(dirname "$foldername")" "$base"
		tar_status=$?

		scp_status=1
		if [ $tar_status -eq 0 ]; then

			CURRENT_REMOTE_USER="$remote_user"
			CURRENT_REMOTE_HOST="$server"
			CURRENT_REMOTE_PATH="$remote_temp"

			scp $scp_opts "$archive" "$remote:$remote_temp"
			scp_status=$?
		fi

		if [ $tar_status -eq 0 ] && [ $scp_status -eq 0 ]; then
			remote_rename "$remote" "$remote_temp" "$remote_target" "$remote_os"
			if [ $? -eq 0 ]; then
				echo -e "\nFolder backed up successfully to $server:$remote_target"
			else
				echo -e "\nError: transfer succeeded but could not finalize the remote folder."
				remote_remove "$remote" "$remote_temp" "$remote_os"
			fi
		else
			echo -e "\nError: server folder backup failed."
			remote_remove "$remote" "$remote_temp" "$remote_os"
		fi

		rm -f "$archive"
		CURRENT_TARGET=""
		CURRENT_REMOTE_USER=""
		CURRENT_REMOTE_HOST=""
		CURRENT_REMOTE_PATH=""
		CURRENT_REMOTE_OS=""
	else
		echo -e "\nInvalid backup type."
		return 1
	fi
}
